services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: always

  # Frontend service
  frontend:
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile.frontend.fixed
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
    restart: always

  # Backend API service
  backend:
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile.backend.fixed
    ports:
      - "5555:5555"  # Expose port for Prisma Studio
    volumes:
      - backend_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/mexico_real_estate
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1d
      - UPLOAD_DIR=uploads
    depends_on:
      - db
    restart: always

  # Database service
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=mexico_real_estate
    restart: always

volumes:
  postgres_data:
  backend_uploads:
